name: CI DemoQA

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Verificar instalación Cypress
      run: |
        ls -l node_modules/.bin/cypress
        npx cypress verify

    - name: Dar permisos a Cypress
      run: chmod +x ./node_modules/.bin/cypress

    - name: Ejecutar tests Cypress
      run: npx cypress run --headless

